apiVersion: apps/v1
kind: Deployment
metadata:
  name: xp-node-graphql-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xp-node-graphql-mongo
  template:
    metadata:
      labels:
        app: xp-node-graphql-mongo
    spec:
      containers:
      - name: xp-node-graphql-mongo
        image: xp-node-graphql-mongo:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: xp-node-graphql-mongo-secrets
              key: MONGO_URI