apiVersion: v1
kind: Service
metadata:
  name: xp-node-graphql-mongo
spec:
  selector:
    app: xp-node-graphql-mongo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer